### ISSUE TITLE
Issue building Building Haste Map

### ISSUE THREAD

**Issue by vouldjeff** [cssivision/react-native-qrcode#1]
I am getting a build error,
that some react-native modules are duplicated. However, when I delete the react-native node module from the qrcode node_modules folder everything was fixed. I think you have to remove the react-native dependency!

**Comment by cssivision** [comment]
this module is dependent on react-native version ^0.12.0, but now react-native version is 0.14.2, so you will duplicate react-native modules. to solve this problem, remove react-native dependency for this module is a solution. when you use this module, you must have react-native module install.
