### ISSUE TITLE
how to save the generated qr code as image

### ISSUE THREAD

**Issue by shaikhussian** [cssivision/react-native-qrcode#10]
hai i tried your  module it is helpful but i have a doubt that how to save the generated qr code as image

**Comment by shaikhussian** [comment]
please give me response

**Comment by cssivision** [comment]
this module is only writed to demonstrate qrcode.

**Comment by shaikhussian** [comment]
can i use on change here

**Comment by Naoto-Ida** [comment]
This would require saving the image from a `<WebView>` component.
