### ISSUE TITLE
QR Code is not rendered in RN 0.37

### ISSUE THREAD

**Issue by d-moreira** [cssivision/react-native-qrcode#17]
Hi there,

as of React Native [`v0.37.0`](https://github.com/facebook/react-native/releases/tag/v0.37.0) the QR Code is no longer rendered. 

Anyone with the same problem?

**Comment by jjzazuet** [comment]
Yes. Same here.

**Comment by cssivision** [comment]
android or ios?

**Comment by jjzazuet** [comment]
@cssivision I *think* both. But for sure iOS exposes the problem. Thanks!

**Comment by cssivision** [comment]
but i do not have this problem, when use in v0.37.0

**Comment by cssivision** [comment]
please get me the example @jjzazuet

**Comment by d-moreira** [comment]
Hi @cssivision,

you can reproduce the issue in iOS with a simple component:

```
export default class Test extends Component {
  render() {
    return (
      <View>
        <QRCode
          value='This is a test QR Code.'
          size={200}
          bgColor='purple'
          fgColor='white'/>
      </View>
    );
  }
}
```

**Comment by cssivision** [comment]
i will fix this, thanks!
