### ISSUE TITLE
Can´t generate QRCode

### ISSUE THREAD

**Issue by BigPun86** [cssivision/react-native-qrcode#2]
![screen shot 2015-12-29 at 18 47 10](https://cloud.githubusercontent.com/assets/7880624/12038960/b1558270-ae5c-11e5-93c1-db2faa9f85ea.png)

**Comment by BigPun86** [comment]
Okay fixed it by replaceing the WebView in Canvas.js with 
[webview-android](https://www.npmjs.com/package/react-native-webview-android)

**Comment by cssivision** [comment]
use the lastest version, this version already support android.

**Comment by MrPluto** [comment]
can generate QRCode but cant recognize
