### ISSUE TITLE
react package  has encountered  an internal  error   for rn40

### ISSUE THREAD

**Issue by qinghantang** [cssivision/react-native-qrcode#22]
it work  well when i  delete the import

**Comment by cssivision** [comment]
what means?

**Comment by qinghantang** [comment]
import QRCode from 'react-native-qrcode';

it  print the error  when i  import

**Comment by qinghantang** [comment]
i  cannot see the detail ,once i  delete the sentence  it works well

**Comment by Lomse** [comment]
I'm having the same error. With **import QRCode from 'react-native-qrcode';** uncommented, it shows {"type":"InternalError", "message":"react-packager has encountered an internal error, please check your terminal error output for more details"}. The funny thing is that the terminal is empty. 
![screen shot 2017-04-02 at 5 23 46 pm](https://cloud.githubusercontent.com/assets/4754182/24589400/281e1e4a-17c9-11e7-8c03-8df4484e6f36.png)
![Uploading Screen Shot 2017-04-02 at 5.24.06 PM.png…]()

**Comment by yuguangmao** [comment]
me 2

**Comment by zrzhit** [comment]
i also have the same error

**Comment by choleece** [comment]
me too.so i uninstall the qrcode

**Comment by cssivision** [comment]
restart with `react-native run-ios` will work fine, i do not find the reason

**Comment by choleece** [comment]
I got it on android.thx@cssivision

**Comment by nikolaymelezhik** [comment]
In my case, I have terminated the react-native console and started in once again
