### ISSUE TITLE
can generate QRCode but cant recognize

### ISSUE THREAD

**Issue by MrPluto** [cssivision/react-native-qrcode#3]
:arrow_up:

**Comment by AwesomeJerry** [comment]
somehow  it's broken.

**Comment by AwesomeJerry** [comment]
Since it's broken somehow, I made one with react-native-art, and it looks performant than a webview.
Please give it a try.
https://github.com/AwesomeJerry/react-native-qrcode-svg

**Comment by timzaak** [comment]
there are some bugs about how to generate it. But I cannot find why.

**Comment by timzaak** [comment]
solve it by pr #13

**Comment by cssivision** [comment]
fixed
