### ISSUE TITLE
Using deprecated 'html' prop in WebView

### ISSUE THREAD

**Issue by nHiRanZ** [cssivision/react-native-qrcode#7]
The `WebView` used in the [Canvas.js](https://github.com/cssivision/react-native-qrcode/blob/master/lib/Canvas.js) is using the deprecated `html` prop. Should use the `source` prop instead.

Reference: [WebView Documentation on React-Native](https://facebook.github.io/react-native/docs/webview.html)

**Comment by cssivision** [comment]
updated
