### ISSUE TITLE
QRCode cant show the size as i set.

### ISSUE THREAD

**Issue by PinelliaTime** [cssivision/react-native-qrcode#85]
"react-native": "0.60.5",
"react-native-qrcode": "^0.2.7",

When first open the page,you will see the follow image:
![image](https://user-images.githubusercontent.com/41352992/66698268-f824d800-ed0e-11e9-8a48-81d50363a997.png)

When i click the code twice,it will change to the size as i set:
![image](https://user-images.githubusercontent.com/41352992/66698274-007d1300-ed0f-11e9-91fa-b55fb41fd8ba.png)

So,how can i do to make sure the code size become as i set?

**Comment by PinelliaTime** [comment]
I have found a method to resolve this problem
open node_modules>react-native-qrcode>lib>Canvas.js，add the following code inside the red box:
`<meta name='viewport' content='width=device-width, initial-scale=1' />`
![image](https://user-images.githubusercontent.com/41352992/66728320-b57e0f80-ee76-11e9-8390-891d9a6f47f0.png)
Add the following code inside the red box

**Comment by willymulyana** [comment]
thanks, it works. I use:
"react-native": "0.61.4",
"react-native-qrcode": "^0.2.7",
