### ISSUE TITLE
WebView moved to react-native-webview

### ISSUE THREAD

**Issue by chamodKanishka** [cssivision/react-native-qrcode#89]
when using react native new update for generate qr code . its shows WebView moved to react-native-webview. but without using webview

**Comment by anchengjian** [comment]
> THIS PROJECT IS NO LONGER MAINTAINED

So: [react-native-qrcode2](https://github.com/anchengjian/react-native-qrcode)

**Comment by chamodKanishka** [comment]
thanks for metion that. but im currently moved to qr code generator. but im not satisfy with that. so surely i'll try this.
